line-length = 100
target-version = "py38"
output-format = "concise"

[lint]
select = ["ALL"]
ignore = [
    "COM812", "ISC001", # conflicts with formatter
    "D203", "D212", "D213", "D214", "D215",  # conflicts with PEP257-convention (A)
    "D404", "D405", "D406", "D407", "D408", "D409",  # conflicts with PEP257-convention (B)
    "D410", "D411", "D413", "D415", "D416", "D417",  # conflicts with PEP257-convention (C)
]

[lint.per-file-ignores]
"*/tests/**" = ["ARG", "S", "D", "T201"]
"*/examples/**" = [
    "INP001", # no namespace
    "T201",   # allow print
]

[lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[lint.isort]
force-single-line = true

[lint.pyupgrade]
keep-runtime-typing = true

[lint.pydocstyle]
convention = "pep257"

[format] # per default like Black
docstring-code-format = true
