name: Test for Quality Control

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-22.04 # TODO: -latest was 20.04 and had old packages

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Set up Python 3.11 🐍
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies 🔧
        run: sudo apt install cppcheck
        # NOTE: cppcheck is needed for pre-commit

      - name: Run Pre-Commit Tests 🧪
        uses: pre-commit/action@v3.0.1
