name: Release firmware

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  call-build-msp:
    uses: ./.github/workflows/build_msp.yaml
  call-build-nrf:
    uses: ./.github/workflows/build_nrf.yaml
  run-quality-assurance:
    uses: ./.github/workflows/qa_tests.yaml
  release-firmware:
    runs-on: ubuntu-latest
    needs:
      - run-quality-assurance
      - call-build-msp
      - call-build-nrf
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - run: mkdir -p content

      - uses: actions/download-artifact@v4
        with:
          path: content/

      - run: cp ${{ github.workspace }}/metadata_fw.yaml content/
      - run: zip -7 -r firmwares.zip content/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: firmwares.zip
